name: Program Deploy

on:
  workflow_dispatch:
    inputs:
      DEPLOY_ENV:
        description: "The environment to deploy (testnet / devnet / mainnet)"
        default: "devnet"
      PROGRAM_NAME:
        description: ""
        default: "helloworld"
      PROGRAM_COMMIT:
        description: ""
        default: "017db45c25e06d6b5f265b48b61b9c64a00e6fc6"
      VERSION:
        description: ""
        default: ""

jobs:
  trigger-deploy:
    name: "${{inputs.PROGRAM_NAME}}-${{inputs.DEPLOY_ENV}} Deploy"
    runs-on: ubuntu-latest
    environment: ${{inputs.DEPLOY_ENV}}
    steps:
      - id: program-name
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{inputs.PROGRAM_NAME}}
      - name: Set Env Vars
        id: set-envs
        run: |
          echo "program_rpc=${{ steps.program-name.outputs.uppercase }}_RPC_URL" >> $GITHUB_ENV

#      - name: Trigger Deployer-Dispatch Job
#        uses: mvasigh/dispatch-action@main
#        with:
#          token: ${{ secrets.DEPLOYER_PAT }}
#          repo: Deployer-Dispatch
#          owner: metaplex-foundation
#          event_type: deploy_trigger
#          message: |
#            {
#              "PROGRAM_RPC_URL":"${{ secrets[env.program_rpc] }}",
#              "PROGRAM_NAME":"${{ inputs.PROGRAM_NAME }}",
#              "PROGRAM_COMMIT":"${{ inputs.PROGRAM_COMMIT }}",
#              "DEPLOY_ENV":"${{ inputs.DEPLOY_ENV }}"
#            }

      - name: INIT WORKFLOW - Dispatch init event to REMOTE repository
        if: github.event.action != 'Deployer Workflow Response'
        run: |
          curl -X POST https://api.github.com/repos/metaplex-foundation/Deployer-Dispatch/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.DEPLOYER_PAT }} \
          --data '{"event_type": "Start Deployment", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'", "PROGRAM_RPC_URL":"${{ secrets[env.program_rpc] }}", "PROGRAM_NAME":"${{ inputs.PROGRAM_NAME }}", "PROGRAM_COMMIT":"${{ inputs.PROGRAM_COMMIT }}", "DEPLOY_ENV":"${{ inputs.DEPLOY_ENV }}" }}'
      - name: RESPONSE - Response event from REMOTE repository
        if: github.event.action == 'Deployer Workflow Response'
        run: |
          echo "RESPONSE received from '${{ github.event.client_payload.repository }}'"
          curl -X POST https://api.github.com/repos/metaplex-foundation/Deployer-Dispatch/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.DEPLOYER_PAT }} \
          --data '{"event_type": "Start Deployment", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'", "PROGRAM_RPC_URL":"${{ secrets[env.program_rpc] }}", "PROGRAM_NAME":"${{ inputs.PROGRAM_NAME }}", "PROGRAM_COMMIT":"${{ inputs.PROGRAM_COMMIT }}", "DEPLOY_ENV":"${{ inputs.DEPLOY_ENV }}" }}'


      - name: Deploy Parameters
        id: deploy_parameters
        run: |
          echo "PROGRAM_NAME: ${{ inputs.PROGRAM_NAME }}" >> $GITHUB_STEP_SUMMARY
          echo "PROGRAM_COMMIT: ${{ inputs.PROGRAM_COMMIT }}" >> $GITHUB_STEP_SUMMARY
          echo "DEPLOY_ENV: ${{ inputs.DEPLOY_ENV }}" >> $GITHUB_STEP_SUMMARY