name: Program Deploy

on:
  workflow_dispatch:
    inputs:
      DEPLOY_ENV:
        description: "The environment to deploy (testnet / devnet / mainnet)"
        default: "devnet"
      PROGRAM_NAME:
        description: ""
        default: "helloworld"
      PROGRAM_COMMIT:
        description: ""
        default: "017db45c25e06d6b5f265b48b61b9c64a00e6fc6"
      VERSION:
        description: ""
        default: ""

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-20.04
    steps:
      - id: program_name
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{inputs.PROGRAM_NAME}}
      - name: Set Env Vars
        id: prepare-step
        run: |
          echo "PROGRAM_RPC=${{ steps.program_name.outputs.uppercase }}_RPC_URL" >> $GITHUB_ENV

  trigger-deploy:
    name: "${{inputs.PROGRAM_NAME}}-${{inputs.DEPLOY_ENV}} Deploy"
    runs-on: ubuntu-latest
    environment: ${{inputs.DEPLOY_ENV}}
    steps:
      - name: Trigger Deployer-Dispatch Job
        uses: mvasigh/dispatch-action@main
        with:
          token: ${{ secrets.DEPLOYER_PAT }}
          repo: Deployer-Dispatch
          owner: metaplex-foundation
          event_type: deploy_trigger
          message: |
            {
              "PROGRAM_RPC_URL":"${{ secrets[env.PROGRAM_RPC] }}",
              "PROGRAM_NAME":"${{ inputs.PROGRAM_NAME }}",
              "PROGRAM_COMMIT":"${{ inputs.PROGRAM_COMMIT }}",
              "DEPLOY_ENV":"${{ inputs.DEPLOY_ENV }}"
            }